language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.37.0 # MSRV

matrix:
  include:
    - name: Clippy
      rust: nightly
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy --tests -- -D clippy::all

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  # --no-default-features for spec
  - cargo build --verbose --manifest-path spec/Cargo.toml --no-default-features
  - cargo test --verbose --manifest-path spec/Cargo.toml --no-default-features
