language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose --all
    # `--all --no-default-features` does not work intuitively
    # https://github.com/rust-lang/cargo/issues/5364
  - cargo test --verbose --manifest-path spec/Cargo.toml --no-default-features
