language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.37.0 # MSRV

matrix:
  include:
    - name: Clippy
      rust: nightly
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy --tests -- -D clippy::all

script:
  - cargo test --verbose --all
  # --no-default-features for environ-str
  - cargo test --verbose --manifest-path environ-str/Cargo.toml --no-default-features
  # --no-default-features for image-spec
  - cargo test --verbose --manifest-path image-spec/Cargo.toml --no-default-features
  # --no-default-features for runtime-config
  - cargo test --verbose --manifest-path runtime-config/Cargo.toml --no-default-features
