[package]
name = "oci-runtime-config"
version = "0.1.0"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]
edition = "2018"

[features]
default = ["serde"]

[dependencies]
serde = { version = "1.0.98", features = ["derive"], optional = true }
