[package]
name = "oci-image-unpack"
version = "0.1.0"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]
edition = "2018"

[dependencies]
image-spec = { package = "oci-image-spec", path = "../image-spec" }
